blockchain_warehouse: 
  target: dev
  outputs:
    dev:
      type: duckdb
      
      path: "md:crypto_db?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      extensions:
        - motherduck
