name: Crypto Cloud Pipeline

on:
  schedule:
    - cron: '0 9 * * *' 
  workflow_dispatch:   

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip uninstall dbt-core dbt-duckdb -y
          pip install requests pandas python-dotenv
          pip install dbt-duckdb==1.8.2 duckdb==1.4.4 --force-reinstall

      - name: Ejecutar Ingesta (Python)
        env:
          motherduck_token: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: python extract_data.py

      - name: Install dbt Dependencies
        env:
          motherduck_token: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: python -m dbt.cli.main deps --profiles-dir .

      - name: Ejecutar dbt
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          dbt clean          
          dbt deps            
          dbt build

      - name: 🧪 Run Data Tests (CI)
        env:
          motherduck_token: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: python -m dbt.cli.main test --profiles-dir .

      - name: 🚀 Deploy Transformations (CD)
        env:
          motherduck_token: ${{ secrets.MOTHERDUCK_TOKEN }}
        
        run: python -m dbt.cli.main run --profiles-dir . || true