version: 2

models:
  - name: mart_crypto_overview
    description: "Tabla final para el equipo de negocio que analiza la distribución de precios."
    columns:
      - name: coin_name
        description: "Nombre de la criptomoneda en mayúsculas."
      - name: percent_of_portfolio
        description: "Peso de la moneda respecto al valor sumado de todas las monedas trackeadas."